apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  selector:
    matchLabels:
      app: k8s-doc-example
  replicas: 1
  template:
    metadata:
      name: k8s-doc-example
      labels:
        app: k8s-doc-example
    spec:
      containers:
        - name: k8s-doc-example
          image: local/devops-test-example:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  type: NodePort
  selector:
    app: k8s-doc-example
  ports:
    - name: http
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080
