apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test
  labels:
    app: docker-test
spec:
  selector:
    matchLabels:
      app: docker-test
  replicas: 1
  template:
    metadata:
      name: docker-test
      labels:
        app: docker-test
    spec:
      containers:
        - name: docker-test
          image: local/docker-test:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8383 # The port that the container is running on in the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: docker-test
  labels:
    app: docker-test
spec:
  type: NodePort
  selector:
    app: docker-test
  ports:
    - name: http
      port: 8383 # The port that the service is running on in the cluster
      targetPort: 8383
