apiVersion: v1
kind: PersistentVolume #providers persistent storage in a cluster
metadata:
  name: docker-test
spec:
  capacity:
    storage: 100Mi #100MB storage
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data