name: CI/CD Workflow

on:
  #Trigger the workflow on push from the master/main branch or on pull request
  push:
    branches: [ master ] # main
  pull_request:
    branches: [ master ] # main

jobs:
  # Build job
  job1:
    name: Build and Deploy to Minikube
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/k8s-doc-example .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl wait --for=condition=Ready pod -l app=k8s-doc-example
          kubectl get all
      - name: Test service URLs
        run: |
          echo "SERVICE_URL=$(minikube service k8s-doc-example --url)"
          kubectl port-forward service/k8s-doc-example 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/k8s-doc-example 8080:8080 &> /dev/null &
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete

  job2:
    name: CI workflow
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run all tests in project
        run: |
          mvn compile && mvn test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKPUB_SECRET }}
      - name: Build and publish updated image
        run: |
          mvn package
          docker build . --tag ghcr.io/KisKova/k8s-doc-example:latest
          docker push ghcr.io/KisKova/k8s-doc-example:latest