name: CI/CD Workflow

on:
  #Trigger the workflow on push from the master/main branch or on pull request
  push:
    branches: [ master ] # main
  pull_request:
    branches: [ master ] # main

jobs:
  # Build job
  job1:
    name: CD Workflow
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/k8s-doc-example .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl wait --for=condition=Ready pod -l app=k8s-doc-example
          kubectl get all
      - name: Test service URLs
        run: |
          echo "SERVICE_URL=$(minikube service k8s-doc-example --url)"
          kubectl port-forward service/k8s-doc-example 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/k8s-doc-example 8080:8080 &> /dev/null &
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete

  job2:
    name: CI Workflow

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kiskova/k8s-doc-example:latest .

      - name: Push Docker image
        run: docker push kiskova/k8s-doc-example:latest

